author = Artur Tarassow
email = atecon@cryptolab.net
version = 0.3
date = 2018-11-10
description = Simple forecasting methods
tags = C53
min-version = 2018a
data-requirement = needs-time-series-data
gui-main = avgfc_gui
label = naive forecast(s)
menu-attachment = MAINWIN/Model/TSModels
public = meanf rwf snaive avgfc_gui fcplot smeanf ar1f avgfc NaiveThroughTime nttplot
menu-only = avgfc_gui 
help = naiveFC.pdf
sample-script = naiveFC_sample.inp
